services:
  db:
    image: mysql:8.0.29
    restart: unless-stopped
    container_name: db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estoque_mercado
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://user:user@db:3306/estoque_mercado

volumes:
  mysql_data:
