services:
  # 1. Aplicação Flask (Docker)
  - type: web
    name: estoque-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromService:
          name: estoque-db
          property: connectionString
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_PHONE
        sync: false
      - key: SENHA_JWT
        sync: false

  # 2. Banco de Dados PostgreSQL
  - type: database
    name: estoque-db
    databaseType: postgres
    plan: free
    region: oregon
    postgresVersion: "15"
